### ISSUE TITLE
open speaker screen when click on a speaker in talk details page

### ISSUE THREAD

**Issue by patcito** [react-europe/react-europe-2018-mobile#3]
When you click on one of the user below, take the user to the speaker detail screen (which is the same screen but with an emphasis on the speaker), check the Speakers list screen, it's the same link.

![2018-03-18](https://user-images.githubusercontent.com/26435/37564962-87c0dd0c-2aa0-11e8-907d-59a2731caa1a.png)

**Comment by aehp20** [comment]
Ticket resolved!
